// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: nvmf_tcp.proto

package nvmf_tcp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Create device NVMe/TCP-specific parameters
type DeviceParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Subsystem NQN
	Subnqn string `protobuf:"bytes,1,opt,name=subnqn,proto3" json:"subnqn,omitempty"`
	// Address family ("ipv4", "ipv6")
	Adrfam string `protobuf:"bytes,2,opt,name=adrfam,proto3" json:"adrfam,omitempty"`
	// Transport address
	Traddr string `protobuf:"bytes,3,opt,name=traddr,proto3" json:"traddr,omitempty"`
	// Transport service ID (port number)
	Trsvcid string `protobuf:"bytes,4,opt,name=trsvcid,proto3" json:"trsvcid,omitempty"`
	// Allow any host to connect
	AllowAnyHost bool `protobuf:"varint,5,opt,name=allow_any_host,json=allowAnyHost,proto3" json:"allow_any_host,omitempty"`
	// List of host NQNs that are allowed to connect to the subsystem (if
	// allow_any_host is false)
	Hosts []string `protobuf:"bytes,6,rep,name=hosts,proto3" json:"hosts,omitempty"`
}

func (x *DeviceParameters) Reset() {
	*x = DeviceParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvmf_tcp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceParameters) ProtoMessage() {}

func (x *DeviceParameters) ProtoReflect() protoreflect.Message {
	mi := &file_nvmf_tcp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceParameters.ProtoReflect.Descriptor instead.
func (*DeviceParameters) Descriptor() ([]byte, []int) {
	return file_nvmf_tcp_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceParameters) GetSubnqn() string {
	if x != nil {
		return x.Subnqn
	}
	return ""
}

func (x *DeviceParameters) GetAdrfam() string {
	if x != nil {
		return x.Adrfam
	}
	return ""
}

func (x *DeviceParameters) GetTraddr() string {
	if x != nil {
		return x.Traddr
	}
	return ""
}

func (x *DeviceParameters) GetTrsvcid() string {
	if x != nil {
		return x.Trsvcid
	}
	return ""
}

func (x *DeviceParameters) GetAllowAnyHost() bool {
	if x != nil {
		return x.AllowAnyHost
	}
	return false
}

func (x *DeviceParameters) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

var File_nvmf_tcp_proto protoreflect.FileDescriptor

var file_nvmf_tcp_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6e, 0x76, 0x6d, 0x66, 0x5f, 0x74, 0x63, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x73, 0x6d, 0x61, 0x2e, 0x6e, 0x76, 0x6d, 0x66, 0x5f, 0x74, 0x63, 0x70, 0x22, 0xb0,
	0x01, 0x0a, 0x10, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x6e, 0x71, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x75, 0x62, 0x6e, 0x71, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x64, 0x72, 0x66, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x64, 0x72,
	0x66, 0x61, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x72, 0x61, 0x64, 0x64, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x72, 0x73, 0x76, 0x63, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72,
	0x73, 0x76, 0x63, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x61,
	0x6e, 0x79, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x61,
	0x6c, 0x6c, 0x6f, 0x77, 0x41, 0x6e, 0x79, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x68,
	0x6f, 0x73, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x68, 0x6f, 0x73, 0x74,
	0x73, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x70, 0x64, 0x6b, 0x2f, 0x73, 0x6d, 0x61, 0x2d, 0x67, 0x6f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6e, 0x76, 0x6d, 0x66, 0x5f, 0x74, 0x63, 0x70,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nvmf_tcp_proto_rawDescOnce sync.Once
	file_nvmf_tcp_proto_rawDescData = file_nvmf_tcp_proto_rawDesc
)

func file_nvmf_tcp_proto_rawDescGZIP() []byte {
	file_nvmf_tcp_proto_rawDescOnce.Do(func() {
		file_nvmf_tcp_proto_rawDescData = protoimpl.X.CompressGZIP(file_nvmf_tcp_proto_rawDescData)
	})
	return file_nvmf_tcp_proto_rawDescData
}

var file_nvmf_tcp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nvmf_tcp_proto_goTypes = []interface{}{
	(*DeviceParameters)(nil), // 0: sma.nvmf_tcp.DeviceParameters
}
var file_nvmf_tcp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nvmf_tcp_proto_init() }
func file_nvmf_tcp_proto_init() {
	if File_nvmf_tcp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nvmf_tcp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nvmf_tcp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nvmf_tcp_proto_goTypes,
		DependencyIndexes: file_nvmf_tcp_proto_depIdxs,
		MessageInfos:      file_nvmf_tcp_proto_msgTypes,
	}.Build()
	File_nvmf_tcp_proto = out.File
	file_nvmf_tcp_proto_rawDesc = nil
	file_nvmf_tcp_proto_goTypes = nil
	file_nvmf_tcp_proto_depIdxs = nil
}
