// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: virtio_blk.proto

package virtio_blk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Physical function index
	PhysicalId uint32 `protobuf:"varint,1,opt,name=physical_id,json=physicalId,proto3" json:"physical_id,omitempty"`
	// Virtual function index
	VirtualId uint32 `protobuf:"varint,2,opt,name=virtual_id,json=virtualId,proto3" json:"virtual_id,omitempty"`
}

func (x *DeviceParameters) Reset() {
	*x = DeviceParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtio_blk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceParameters) ProtoMessage() {}

func (x *DeviceParameters) ProtoReflect() protoreflect.Message {
	mi := &file_virtio_blk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceParameters.ProtoReflect.Descriptor instead.
func (*DeviceParameters) Descriptor() ([]byte, []int) {
	return file_virtio_blk_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceParameters) GetPhysicalId() uint32 {
	if x != nil {
		return x.PhysicalId
	}
	return 0
}

func (x *DeviceParameters) GetVirtualId() uint32 {
	if x != nil {
		return x.VirtualId
	}
	return 0
}

var File_virtio_blk_proto protoreflect.FileDescriptor

var file_virtio_blk_proto_rawDesc = []byte{
	0x0a, 0x10, 0x76, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x5f, 0x62, 0x6c, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x73, 0x6d, 0x61, 0x2e, 0x76, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x5f, 0x62,
	0x6c, 0x6b, 0x22, 0x52, 0x0a, 0x10, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63,
	0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x70, 0x68, 0x79,
	0x73, 0x69, 0x63, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x72, 0x74, 0x75,
	0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x76, 0x69, 0x72,
	0x74, 0x75, 0x61, 0x6c, 0x49, 0x64, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x70, 0x64, 0x6b, 0x2f, 0x73, 0x6d, 0x61, 0x2d, 0x67, 0x6f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x76, 0x69, 0x72,
	0x74, 0x69, 0x6f, 0x5f, 0x62, 0x6c, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_virtio_blk_proto_rawDescOnce sync.Once
	file_virtio_blk_proto_rawDescData = file_virtio_blk_proto_rawDesc
)

func file_virtio_blk_proto_rawDescGZIP() []byte {
	file_virtio_blk_proto_rawDescOnce.Do(func() {
		file_virtio_blk_proto_rawDescData = protoimpl.X.CompressGZIP(file_virtio_blk_proto_rawDescData)
	})
	return file_virtio_blk_proto_rawDescData
}

var file_virtio_blk_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_virtio_blk_proto_goTypes = []interface{}{
	(*DeviceParameters)(nil), // 0: sma.virtio_blk.DeviceParameters
}
var file_virtio_blk_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_virtio_blk_proto_init() }
func file_virtio_blk_proto_init() {
	if File_virtio_blk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_virtio_blk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_virtio_blk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_virtio_blk_proto_goTypes,
		DependencyIndexes: file_virtio_blk_proto_depIdxs,
		MessageInfos:      file_virtio_blk_proto_msgTypes,
	}.Build()
	File_virtio_blk_proto = out.File
	file_virtio_blk_proto_rawDesc = nil
	file_virtio_blk_proto_goTypes = nil
	file_virtio_blk_proto_depIdxs = nil
}
