// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: nvmf.proto

package nvmf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines an address of an NVMeoF endpoint
type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Transport type ("rdma" or "tcp")
	Trtype string `protobuf:"bytes,1,opt,name=trtype,proto3" json:"trtype,omitempty"`
	// Transport address (IP)
	Traddr string `protobuf:"bytes,2,opt,name=traddr,proto3" json:"traddr,omitempty"`
	// Transport service identifier (port number)
	Trsvcid string `protobuf:"bytes,3,opt,name=trsvcid,proto3" json:"trsvcid,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvmf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_nvmf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_nvmf_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetTrtype() string {
	if x != nil {
		return x.Trtype
	}
	return ""
}

func (x *Address) GetTraddr() string {
	if x != nil {
		return x.Traddr
	}
	return ""
}

func (x *Address) GetTrsvcid() string {
	if x != nil {
		return x.Trsvcid
	}
	return ""
}

// NVMeoF connection using discovery service
type VolumeDiscoveryParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// One or more discovery endpoints
	DiscoveryEndpoints []*Address `protobuf:"bytes,1,rep,name=discovery_endpoints,json=discoveryEndpoints,proto3" json:"discovery_endpoints,omitempty"`
}

func (x *VolumeDiscoveryParameters) Reset() {
	*x = VolumeDiscoveryParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvmf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeDiscoveryParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeDiscoveryParameters) ProtoMessage() {}

func (x *VolumeDiscoveryParameters) ProtoReflect() protoreflect.Message {
	mi := &file_nvmf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeDiscoveryParameters.ProtoReflect.Descriptor instead.
func (*VolumeDiscoveryParameters) Descriptor() ([]byte, []int) {
	return file_nvmf_proto_rawDescGZIP(), []int{1}
}

func (x *VolumeDiscoveryParameters) GetDiscoveryEndpoints() []*Address {
	if x != nil {
		return x.DiscoveryEndpoints
	}
	return nil
}

// Describes connection parameters for an NVMeoF volume (namespace)
type VolumeConnectionParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Subsystem that the volume is exposed through.  A volume with a given
	// GUID/UUID won't be created if it's attached to a different subsystem.  This
	// field is optional and can be left empty.
	Subnqn string `protobuf:"bytes,1,opt,name=subnqn,proto3" json:"subnqn,omitempty"`
	// Host NQN to use when connecting to the subsystem exposing the volume (and,
	// if using discovery, to the discovery subsystem too).
	Hostnqn string `protobuf:"bytes,2,opt,name=hostnqn,proto3" json:"hostnqn,omitempty"`
	// Types that are assignable to ConnectionParams:
	//
	//	*VolumeConnectionParameters_Discovery
	ConnectionParams isVolumeConnectionParameters_ConnectionParams `protobuf_oneof:"connection_params"`
}

func (x *VolumeConnectionParameters) Reset() {
	*x = VolumeConnectionParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nvmf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeConnectionParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeConnectionParameters) ProtoMessage() {}

func (x *VolumeConnectionParameters) ProtoReflect() protoreflect.Message {
	mi := &file_nvmf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeConnectionParameters.ProtoReflect.Descriptor instead.
func (*VolumeConnectionParameters) Descriptor() ([]byte, []int) {
	return file_nvmf_proto_rawDescGZIP(), []int{2}
}

func (x *VolumeConnectionParameters) GetSubnqn() string {
	if x != nil {
		return x.Subnqn
	}
	return ""
}

func (x *VolumeConnectionParameters) GetHostnqn() string {
	if x != nil {
		return x.Hostnqn
	}
	return ""
}

func (m *VolumeConnectionParameters) GetConnectionParams() isVolumeConnectionParameters_ConnectionParams {
	if m != nil {
		return m.ConnectionParams
	}
	return nil
}

func (x *VolumeConnectionParameters) GetDiscovery() *VolumeDiscoveryParameters {
	if x, ok := x.GetConnectionParams().(*VolumeConnectionParameters_Discovery); ok {
		return x.Discovery
	}
	return nil
}

type isVolumeConnectionParameters_ConnectionParams interface {
	isVolumeConnectionParameters_ConnectionParams()
}

type VolumeConnectionParameters_Discovery struct {
	// Connection through discovery service
	Discovery *VolumeDiscoveryParameters `protobuf:"bytes,3,opt,name=discovery,proto3,oneof"`
}

func (*VolumeConnectionParameters_Discovery) isVolumeConnectionParameters_ConnectionParams() {}

var File_nvmf_proto protoreflect.FileDescriptor

var file_nvmf_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6e, 0x76, 0x6d, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x6d,
	0x61, 0x2e, 0x6e, 0x76, 0x6d, 0x66, 0x22, 0x53, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x72, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x72, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x72, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x72, 0x61, 0x64, 0x64,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x73, 0x76, 0x63, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x73, 0x76, 0x63, 0x69, 0x64, 0x22, 0x5f, 0x0a, 0x19, 0x56,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x42, 0x0a, 0x13, 0x64, 0x69, 0x73, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x6d, 0x61, 0x2e, 0x6e, 0x76, 0x6d, 0x66,
	0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x12, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x79, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0xa8, 0x01, 0x0a,
	0x1a, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x75, 0x62, 0x6e, 0x71, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x75, 0x62,
	0x6e, 0x71, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x71, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x71, 0x6e, 0x12, 0x43, 0x0a,
	0x09, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x73, 0x6d, 0x61, 0x2e, 0x6e, 0x76, 0x6d, 0x66, 0x2e, 0x56, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x73, 0x48, 0x00, 0x52, 0x09, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x79, 0x42, 0x13, 0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x70, 0x64, 0x6b, 0x2f, 0x73, 0x6d, 0x61, 0x2d, 0x67,
	0x6f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x6e, 0x76,
	0x6d, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nvmf_proto_rawDescOnce sync.Once
	file_nvmf_proto_rawDescData = file_nvmf_proto_rawDesc
)

func file_nvmf_proto_rawDescGZIP() []byte {
	file_nvmf_proto_rawDescOnce.Do(func() {
		file_nvmf_proto_rawDescData = protoimpl.X.CompressGZIP(file_nvmf_proto_rawDescData)
	})
	return file_nvmf_proto_rawDescData
}

var file_nvmf_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nvmf_proto_goTypes = []interface{}{
	(*Address)(nil),                    // 0: sma.nvmf.Address
	(*VolumeDiscoveryParameters)(nil),  // 1: sma.nvmf.VolumeDiscoveryParameters
	(*VolumeConnectionParameters)(nil), // 2: sma.nvmf.VolumeConnectionParameters
}
var file_nvmf_proto_depIdxs = []int32{
	0, // 0: sma.nvmf.VolumeDiscoveryParameters.discovery_endpoints:type_name -> sma.nvmf.Address
	1, // 1: sma.nvmf.VolumeConnectionParameters.discovery:type_name -> sma.nvmf.VolumeDiscoveryParameters
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nvmf_proto_init() }
func file_nvmf_proto_init() {
	if File_nvmf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nvmf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvmf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeDiscoveryParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nvmf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeConnectionParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_nvmf_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*VolumeConnectionParameters_Discovery)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nvmf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nvmf_proto_goTypes,
		DependencyIndexes: file_nvmf_proto_depIdxs,
		MessageInfos:      file_nvmf_proto_msgTypes,
	}.Build()
	File_nvmf_proto = out.File
	file_nvmf_proto_rawDesc = nil
	file_nvmf_proto_goTypes = nil
	file_nvmf_proto_depIdxs = nil
}
